name: Rebase main-audio
on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update main-audio branch
        run: |
          git fetch --all
          git checkout main-audio
          git rebase main || (git rebase --abort && git rebase main --skip)
          git push --force-with-lease

