name: Rebase main-audio

on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"

      - name: Fetch main-audio branch
        run: git fetch origin main-audio

      - name: Rebase main-audio onto main
        run: git rebase origin/main main-audio

      - name: Push rebased branch
        run: |
          git checkout main-audio
          git push origin main-audio
